### ISSUE TITLE
Fix windows opening to be larger than the screen

### ISSUE THREAD

**Issue by scallyw4g** [scallyw4g/bonsai#47]
Windows created with `WindowLayoutFlag_StartupSize_InferHeight` and `WindowLayoutFlag_StartupSize_InferWidth` can open a larger window than the screen can fit.

It would be nice if the code that did the window setup `stdlib/src/ui/ui.cpp:2366` would be smarter about how large it would make a window.  The screen dimensions are accessable through the `renderer2d *Group` in that function as `Group->ScreenDim`. 

The fix should be as simple as clamping MaxClip to Basis-ScreenDim.  For bonus points, there's a global called `DefaultWIndowSideOffset` .. you could work that in such that there's a nice border between the max edge and the edge of the OS window.

**Comment by Shawnecy** [comment]
A few windows that experience this right now when you start up `game_loader`:

All Entities
![Selection_929](https://github.com/scallyw4g/bonsai/assets/6253755/6a46531d-a23f-48a8-b98a-ec7fdbab9963)

Textures
![Selection_932](https://github.com/scallyw4g/bonsai/assets/6253755/0c896e20-1af4-4717-96bd-6818294fc712)

There are more, but those are sufficient. The Textures window has the added bug of being rendered too high due to be bottom aligned and larger than the screen.
